camel:
  springboot:
    # The Camel context name
    name: CamelRestJpa

mysql:
  service:
    # The host of the MySQL database server, can be customized using
    # the 'MYSQL_SERVICE_HOST' env variable
    host:     localhost
    # The port of the MySQL database server, can be customized using
    # the 'MYSQL_SERVICE_PORT' env variable
    port:     3306
    # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE'
    # env variable
    database: mydb
    username: root
    password:

spring:
  # Spring JDBC configuration
  datasource:
    url:      jdbc:mysql://${mysql.service.host}:${mysql.service.port}/${mysql.service.database}
    username: root #${mysql.service.username}
    password: ${mysql.service.password}

  # Spring Data JPA configuration
  jpa:
    show-sql: false
    
#log4j:
#  rootLogger: INFO#, out
#  appender:
#    out: org.apache.log4j.ConsoleAppender
#    out:
#      layout: org.apache.log4j.PatternLayout
      #layout:
        #ConversionPattern: [%30.30t] %-30.30c{1} %-5p %m%n
        #ConversionPattern: %d [%-15.15t] %-5p %-30.30c{1} - %m%n
#  logger:
#    org:
#      apache:
#        camel: DEBUG